// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_movimentoManual.Data;

namespace api_movimentoManual.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221009203711_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("api_movimentoManual.Model.Produto", b =>
                {
                    b.Property<string>("COD_PRODUTO")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("DES_PRODUTO")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("STA_STATUS")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("COD_PRODUTO");

                    b.ToTable("PRODUTO");

                    b.HasData(
                        new
                        {
                            COD_PRODUTO = "PR01",
                            DES_PRODUTO = "PRD 001",
                            STA_STATUS = "A"
                        },
                        new
                        {
                            COD_PRODUTO = "PR02",
                            DES_PRODUTO = "PRD 002",
                            STA_STATUS = "D"
                        },
                        new
                        {
                            COD_PRODUTO = "PR03",
                            DES_PRODUTO = "PRD 003",
                            STA_STATUS = "A"
                        });
                });

            modelBuilder.Entity("api_movimentoManual.Model.Produto_Cosif", b =>
                {
                    b.Property<string>("COD_COSIF")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("COD_PRODUTO")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("COD_CLASSIFICACAO")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("STA_STATUS")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("COD_COSIF", "COD_PRODUTO");

                    b.ToTable("PRODUTO_COSIF");

                    b.HasData(
                        new
                        {
                            COD_COSIF = "PRDCOS001",
                            COD_PRODUTO = "PR01",
                            COD_CLASSIFICACAO = "CL1",
                            STA_STATUS = "A"
                        },
                        new
                        {
                            COD_COSIF = "PRDCOS999",
                            COD_PRODUTO = "PR01",
                            COD_CLASSIFICACAO = "CL999",
                            STA_STATUS = "A"
                        },
                        new
                        {
                            COD_COSIF = "PRDCOS002",
                            COD_PRODUTO = "PR02",
                            COD_CLASSIFICACAO = "CL2",
                            STA_STATUS = "D"
                        },
                        new
                        {
                            COD_COSIF = "PRDCOS003",
                            COD_PRODUTO = "PR03",
                            COD_CLASSIFICACAO = "CL3",
                            STA_STATUS = "A"
                        });
                });

            modelBuilder.Entity("api_movimentoManual.Models.Movimento_Manual", b =>
                {
                    b.Property<int>("DAT_MES")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DAT_ANO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NUM_LANCAMENTO")
                        .HasColumnType("INTEGER");

                    b.Property<string>("COD_PRODUTO")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("COD_COSIF")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("COD_USUARIO")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DAT_MOVIMENTO")
                        .HasColumnType("TEXT");

                    b.Property<string>("DES_DESCRICAO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VAL_VALOR")
                        .HasColumnType("TEXT");

                    b.HasKey("DAT_MES", "DAT_ANO", "NUM_LANCAMENTO", "COD_PRODUTO", "COD_COSIF");

                    b.ToTable("MOVIMENTO_MANUAL");
                });
#pragma warning restore 612, 618
        }
    }
}
